In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as ply

In [4]:
df=pd.read_csv(
    "IMDB Dataset.csv")

In [5]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

# Lowering

In [6]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [7]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [8]:
df['review']=df['review'].str.lower()

In [9]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# Removing Unwanted Things
- Html tags
- remove url's
- removing punctuations

In [10]:
import re

### HTML Tages

In [11]:
#HTML Tags
def remove_html_tags(text):
    pattern=re.compile('<.*?>')
    return pattern.sub(r'',text)

In [12]:
df['review']=df['review'].apply(remove_html_tags)

In [13]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [14]:
df['review'][2]

'i thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. the plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). while some may be disappointed when they realize this is not match point 2: risk addiction, i thought it was proof that woody allen is still fully in control of the style many of us have grown to love.this was the most i\'d laughed at one of woody\'s comedies in years (dare i say a decade?). while i\'ve never been impressed with scarlet johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.this may not be the crown jewel of his career, but it was wittier than "devil wears prada" and more interesting than "superman" a great comedy to go see with friends.'

### Url's

In [15]:
text1='This is an example of url https://www.linkedin.com/in/deepanshu-verma-217858175/'
text2='This is an example of url http://www.linkedin.com/in/deepanshu-verma-217858175/'
text3='This is an example of url www.google.com'
text4='This is an example of url https://www.linkedin.com/in/deepanshu-verma-217858175/ and this one is another url www.google.com'

In [16]:
# Removing Url's

def remove_url(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'',text)

In [17]:
remove_url(text4)

'This is an example of url  and this one is another url '

### Punctuations

In [18]:
# remove punctutation

In [7]:
import string,time

In [8]:
exclude=string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [9]:
def remove_punctuation(text):
    for j in exclude:
        text=text.replace(j,'')
    return text

In [10]:
text1='hello? i am deepan*&shu$ verm#'

In [11]:
remove_punctuation(text1)

'hello i am deepanshu verm'

In [23]:
df['review']=df['review'].apply(remove_punctuation)

In [24]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

### Chat Word Treatement

# Slang Translation
https://github.com/rishabhverma17/sms_slang_translator/blob/master/slang.txt

In [14]:
f=open('slang.txt','r')
for i in f:
    print(i)
    if '=' in i:
        a=i.split('=')
        print(a)
#     break

AFAIK=As Far As I Know

['AFAIK', 'As Far As I Know\n']
AFK=Away From Keyboard

['AFK', 'Away From Keyboard\n']
ASAP=As Soon As Possible

['ASAP', 'As Soon As Possible\n']
ATK=At The Keyboard

['ATK', 'At The Keyboard\n']
ATM=At The Moment

['ATM', 'At The Moment\n']
A3=Anytime, Anywhere, Anyplace

['A3', 'Anytime, Anywhere, Anyplace\n']
BAK=Back At Keyboard

['BAK', 'Back At Keyboard\n']
BBL=Be Back Later

['BBL', 'Be Back Later\n']
BBS=Be Back Soon

['BBS', 'Be Back Soon\n']
BFN=Bye For Now

['BFN', 'Bye For Now\n']
B4N=Bye For Now

['B4N', 'Bye For Now\n']
BRB=Be Right Back

['BRB', 'Be Right Back\n']
BRT=Be Right There

['BRT', 'Be Right There\n']
BTW=By The Way

['BTW', 'By The Way\n']
B4=Before

['B4', 'Before\n']
B4N=Bye For Now

['B4N', 'Bye For Now\n']
CU=See You

['CU', 'See You\n']
CUL8R=See You Later

['CUL8R', 'See You Later\n']
CYA=See You

['CYA', 'See You\n']
FAQ=Frequently Asked Questions

['FAQ', 'Frequently Asked Questions\n']
FC=Fingers Crossed

['FC', 'Fingers Crossed\n']
FWIW=For What It's Worth

['FWIW', "For What It's Worth\n"]
FYI=For Your Information

['FYI', 'For Your Information\n']
GAL=Get A Life

['GAL', 'Get A Life\n']
GG=Good Game

['GG', 'Good Game\n']
GN=Good Night

['GN', 'Good Night\n']
GMTA=Great Minds Think Alike

['GMTA', 'Great Minds Think Alike\n']
GR8=Great!

['GR8', 'Great!\n']
G9=Genius

['G9', 'Genius\n']
IC=I See

['IC', 'I See\n']
ICQ=I Seek you (also a chat program)

['ICQ', 'I Seek you (also a chat program)\n']
ILU=ILU: I Love You

['ILU', 'ILU: I Love You\n']
IMHO=In My Honest/Humble Opinion

['IMHO', 'In My Honest/Humble Opinion\n']
IMO=In My Opinion

['IMO', 'In My Opinion\n']
IOW=In Other Words

['IOW', 'In Other Words\n']
IRL=In Real Life

['IRL', 'In Real Life\n']
KISS=Keep It Simple, Stupid

['KISS', 'Keep It Simple, Stupid\n']
LDR=Long Distance Relationship

['LDR', 'Long Distance Relationship\n']
LMAO=Laugh My A.. Off

['LMAO', 'Laugh My A.. Off\n']
LOL=Laughing Out Loud

['LOL', 'Laughing Out Loud\n']
LTNS=Long Time No See

['LTNS', 'Long Time No See\n']
L8R=Later

['L8R', 'Later\n']
MTE=My Thoughts Exactly

['MTE', 'My Thoughts Exactly\n']
M8=Mate

['M8', 'Mate\n']
NRN=No Reply Necessary

['NRN', 'No Reply Necessary\n']
OIC=Oh I See

['OIC', 'Oh I See\n']
PITA=Pain In The A..

['PITA', 'Pain In The A..\n']
PRT=Party

['PRT', 'Party\n']
PRW=Parents Are Watching

['PRW', 'Parents Are Watching\n']
QPSA=Que Pasa?

['QPSA', 'Que Pasa?\n']
ROFL=Rolling On The Floor Laughing

['ROFL', 'Rolling On The Floor Laughing\n']
ROFLOL=Rolling On The Floor Laughing Out Loud

['ROFLOL', 'Rolling On The Floor Laughing Out Loud\n']
ROTFLMAO=Rolling On The Floor Laughing My A.. Off

['ROTFLMAO', 'Rolling On The Floor Laughing My A.. Off\n']
SK8=Skate

['SK8', 'Skate\n']
STATS=Your sex and age

['STATS', 'Your sex and age\n']
ASL=Age, Sex, Location

['ASL', 'Age, Sex, Location\n']
THX=Thank You

['THX', 'Thank You\n']
TTFN=Ta-Ta For Now!

['TTFN', 'Ta-Ta For Now!\n']
TTYL=Talk To You Later

['TTYL', 'Talk To You Later\n']
U=You

['U', 'You\n']
U2=You Too

['U2', 'You Too\n']
U4E=Yours For Ever

['U4E', 'Yours For Ever\n']
WB=Welcome Back

['WB', 'Welcome Back\n']
WTF=What The F...

['WTF', 'What The F...\n']
WTG=Way To Go!

['WTG', 'Way To Go!\n']
WUF=Where Are You From?

['WUF', 'Where Are You From?\n']
W8=Wait...

['W8', 'Wait...\n']
7K=Sick:-D Laugher

['7K', 'Sick:-D Laugher\n']
TFW â€“ That feeling when. TFW internet slang often goes in a caption to an image.

MFW â€“ My face when

MRW â€“ My reaction when

IFYP â€“ I feel your pain

LOL â€“ Laughing out loud

TNTL â€“ Trying not to laugh

JK â€“ Just kidding

IDC â€“ I donâ€™t care

ILY â€“ I love you

IMU â€“ I miss you

ADIH â€“ Another day in hell

IDC â€“ I donâ€™t care

ZZZ â€“ Sleeping, bored, tired

WYWH â€“ Wish you were here

TIME â€“ Tears in my eyes

BAE â€“ Before anyone else

FIMH â€“ Forever in my heart

BSAAW â€“ Big smile and a wink

BWL â€“ Bursting with laughter

LMAO â€“ Laughing my a** off

BFF: Best friends forever

CSL â€“ Canâ€™t stop laughing

In [15]:
d={}
try:
    f=open('slang.txt','r')
    for i in f:
        if '=' in i:
            a=i.split('=')
            d[a[0]]=a[1].replace('\n','')
        elif ':' in i:
            a=i.split(':')
            d[a[0]]=a[1].replace('\n','')
        else:
            a=i.split('-')
            d[a[0]]=a[1].replace('\n','')
except:
    pass

In [16]:
d

{'AFAIK': 'As Far As I Know',
 'AFK': 'Away From Keyboard',
 'ASAP': 'As Soon As Possible',
 'ATK': 'At The Keyboard',
 'ATM': 'At The Moment',
 'A3': 'Anytime, Anywhere, Anyplace',
 'BAK': 'Back At Keyboard',
 'BBL': 'Be Back Later',
 'BBS': 'Be Back Soon',
 'BFN': 'Bye For Now',
 'B4N': 'Bye For Now',
 'BRB': 'Be Right Back',
 'BRT': 'Be Right There',
 'BTW': 'By The Way',
 'B4': 'Before',
 'CU': 'See You',
 'CUL8R': 'See You Later',
 'CYA': 'See You',
 'FAQ': 'Frequently Asked Questions',
 'FC': 'Fingers Crossed',
 'FWIW': "For What It's Worth",
 'FYI': 'For Your Information',
 'GAL': 'Get A Life',
 'GG': 'Good Game',
 'GN': 'Good Night',
 'GMTA': 'Great Minds Think Alike',
 'GR8': 'Great!',
 'G9': 'Genius',
 'IC': 'I See',
 'ICQ': 'I Seek you (also a chat program)',
 'ILU': 'ILU: I Love You',
 'IMHO': 'In My Honest/Humble Opinion',
 'IMO': 'In My Opinion',
 'IOW': 'In Other Words',
 'IRL': 'In Real Life',
 'KISS': 'Keep It Simple, Stupid',
 'LDR': 'Long Distance Relationship',
 'LMAO': 'Laugh My A.. Off',
 'LOL': 'Laughing Out Loud',
 'LTNS': 'Long Time No See',
 'L8R': 'Later',
 'MTE': 'My Thoughts Exactly',
 'M8': 'Mate',
 'NRN': 'No Reply Necessary',
 'OIC': 'Oh I See',
 'PITA': 'Pain In The A..',
 'PRT': 'Party',
 'PRW': 'Parents Are Watching',
 'QPSA': 'Que Pasa?',
 'ROFL': 'Rolling On The Floor Laughing',
 'ROFLOL': 'Rolling On The Floor Laughing Out Loud',
 'ROTFLMAO': 'Rolling On The Floor Laughing My A.. Off',
 'SK8': 'Skate',
 'STATS': 'Your sex and age',
 'ASL': 'Age, Sex, Location',
 'THX': 'Thank You',
 'TTFN': 'Ta-Ta For Now!',
 'TTYL': 'Talk To You Later',
 'U': 'You',
 'U2': 'You Too',
 'U4E': 'Yours For Ever',
 'WB': 'Welcome Back',
 'WTF': 'What The F...',
 'WTG': 'Way To Go!',
 'WUF': 'Where Are You From?',
 'W8': 'Wait...',
 '7K': 'Sick:-D Laugher'}

In [17]:
len(d)+21

88

In [18]:
def chat_conversion(text):
    new_text=[]
    for w in text.split():
        if w.upper() in d:
            new_text.append(d[w.upper()])
        else:
            new_text.append(w)
    return ' '.join(new_text)

In [19]:
chat_conversion('asap')

'As Soon As Possible'

# Spelling Correction

In [31]:
# pip install textblob

In [32]:
from textblob import TextBlob

In [33]:
incorrect_text='hello how arte you are you fine ot nioty i am okay'

textBlb=TextBlob(incorrect_text)
textBlb.correct().string

'hello how are you are you fine of not i am okay'

# Removing Stop Words

In [20]:
from nltk.corpus import stopwords

In [35]:
# import nltk
# nltk.download()

In [24]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [37]:
def remove_stop_words(text):
    new_text=[]
    
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
            
    x=new_text[:]
    new_text.clear()
    return " ".join(x)

In [38]:
remove_stop_words('hello i am deepanshu')

'hello   deepanshu'

In [39]:
df['review'].head().apply(remove_stop_words)

0    one    reviewers  mentioned   watching  1 oz e...
1     wonderful little production  filming techniqu...
2     thought    wonderful way  spend time    hot s...
3    basically theres  family   little boy jake thi...
4    petter matteis love   time  money   visually s...
Name: review, dtype: object

# Handling Emoji's

In [40]:
import re

In [41]:
def remove_emoji(text):
    emoji_pattern=re.compile("["
                             u"\U0001F600-\U0001F64F" # emoticons
                             u"\U0001F300-\U0001F5FF" # symbols & pictographs
                             u"\U0001F680-\U0001F6FF" # transport and map symbols
                             u"\U0001F1E0-\U0001F1FF" # flags (ios)
                             u"\U00002702-\U000027B0"
                             u"\U000024C2-\U0001F251"
                             "]+",flags=re.UNICODE)
    return emoji_pattern.sub(r'',text)

In [42]:
remove_emoji("hello this is weired 🥲")

'hello this is weired 🥲'

# Tokenization

### using split function

In [43]:
# 1. word tokenization
sent1='i am going to delhi'
sent1.split()

['i', 'am', 'going', 'to', 'delhi']

In [44]:
# sentence tokenization
sent2='i am goint to delhi. i stayp upto 3 days. Let\'s hope you dont mind'
sent2.split('.')

['i am goint to delhi', ' i stayp upto 3 days', " Let's hope you dont mind"]

In [45]:
# Problems with split function
sent3='i am going to delhi!'
sent3.split()

['i', 'am', 'going', 'to', 'delhi!']

In [46]:
# 2. Regular expression
sent3='i am going to delhi!'
tokens=re.findall("[\w']+",sent3)
tokens

['i', 'am', 'going', 'to', 'delhi']

In [47]:
# 3. nltk approach

In [48]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [49]:
sent3='i am going to delhi!'
word_tokenize(sent3)

['i', 'am', 'going', 'to', 'delhi', '!']

In [50]:
sent4='I have a PH.D in A.I'
sent5='We are to help! mail us at deep@gmail.com'
sent6='A 5km ride cost $10.50'

In [51]:
word_tokenize(sent4)

['I', 'have', 'a', 'PH.D', 'in', 'A.I']

In [52]:
word_tokenize(sent5) # problem with the email

['We', 'are', 'to', 'help', '!', 'mail', 'us', 'at', 'deep', '@', 'gmail.com']

In [53]:
word_tokenize(sent6)

['A', '5km', 'ride', 'cost', '$', '10.50']

In [54]:
# Best Tokenization library is SPACY

In [55]:
# pip install spacy

In [56]:
# !python -m spacy download en_core_web_sm

In [57]:
import spacy

In [58]:
nlp=spacy.load('en_core_web_sm')

In [59]:
doc1=nlp(sent4)
doc2=nlp(sent5)
doc3=nlp(sent6)

In [60]:
for token  in doc2:
    print(token)

We
are
to
help
!
mail
us
at
deep@gmail.com

# Stemming

In [61]:
from nltk.stem.porter import PorterStemmer

In [62]:
ps=PorterStemmer()
def stem_words(text):
        return " ".join([ps.stem(word) for word in text.split()])

In [63]:
sample='walked walks walking walk'

In [64]:
stem_words(sample)

'walk walk walk walk'

In [65]:
text='probably my alltime favorite movie a story of selflessness sacrifice and dedication.'
stem_words(text) # problem with stemming approach

'probabl my alltim favorit movi a stori of selfless sacrific and dedication.'

# Lemmatization

In [66]:
from nltk.stem import WordNetLemmatizer

In [68]:
import nltk

In [74]:
WL=WordNetLemmatizer()
sentence='He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun.'
punctuation='?:!.,;'
sentence_words=nltk.word_tokenize(sentence)
for word in sentence_words:
    if word in punctuation:
        sentence_words.remove(word)
sentence_words
print("{0:20}{1:20}".format('Word','Lemma'))
for word in sentence_words:
    print("{0:20}{1:20}".format(word,WL.lemmatize(word,pos='v')))

Word                Lemma
He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun