In [3]:
import numpy as np
import pandas as pd

In [35]:
df=pd.DataFrame({'Text. No.':['D1','D2','D3','D4'],'Text':['people watch movie','movie watch movie','people write comment','movie write comment']})

In [36]:
df

  Text. No.                  Text
0        D1    people watch movie
1        D2     movie watch movie
2        D3  people write comment
3        D4   movie write comment

In [73]:
np.array(df['Text'])

array(['people watch movie', 'movie watch movie', 'people write comment',
       'movie write comment'], dtype=object)

# Bag Of Words

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

In [39]:
cv=CountVectorizer()
bow=cv.fit_transform(df['Text'])

In [40]:
# vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'movie': 1, 'write': 4, 'comment': 0}

In [41]:
print(bow[0].toarray()) # Document 1
print(bow[1].toarray()) # Document 2
print(bow[2].toarray()) # Document 3
print(bow[3].toarray()) # Documnet 4

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]
[[1 1 0 0 1]]

In [42]:
# for new sentence
cv.transform(['movie watch and write comment of movie ']).toarray() # prediction

array([[1, 2, 0, 1, 1]], dtype=int64)

In [43]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'movie': 1, 'write': 4, 'comment': 0}

In [44]:
# Binary Bag of Words
cv=CountVectorizer(    binary=True,
)
bow=cv.fit_transform(df['Text'])

In [45]:
print(bow[0].toarray()) # Document 1
print(bow[1].toarray()) # Document 2
print(bow[2].toarray()) # Document 3
print(bow[3].toarray()) # Documnet 4

[[0 1 1 1 0]]
[[0 1 0 1 0]]
[[1 0 1 0 1]]
[[1 1 0 0 1]]

# N-grams

In [63]:
# Bi-grams
cv=CountVectorizer(ngram_range=(2,2))
bow=cv.fit_transform(df['Text'])

In [64]:
bow.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]], dtype=int64)

In [50]:
df

  Text. No.                  Text
0        D1    people watch movie
1        D2     movie watch movie
2        D3  people write comment
3        D4   movie write comment

In [59]:
# vocab
print(cv.vocabulary_)

{'people watch': 4, 'watch movie': 8, 'people watch movie': 5, 'movie watch': 0, 'movie watch movie': 1, 'people write': 6, 'write comment': 9, 'people write comment': 7, 'movie write': 2, 'movie write comment': 3}

In [54]:
# Tri-grams
cv=CountVectorizer(ngram_range=(3,3))
bow=cv.fit_transform(df['Text'])
print(cv.vocabulary_)

{'people watch movie': 2, 'movie watch movie': 0, 'people write comment': 3, 'movie write comment': 1}

In [56]:
bow.toarray()

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0]], dtype=int64)

# Tf-Idf

In [87]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [88]:
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['Text']).toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [93]:
tfidf.vocabulary_

{'people': 2, 'watch': 3, 'movie': 1, 'write': 4, 'comment': 0}

In [97]:
tfidf.vocabulary_

{'people': 2, 'watch': 3, 'movie': 1, 'write': 4, 'comment': 0}

In [91]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
['comment' 'movie' 'people' 'watch' 'write']

In [92]:
1/3

0.3333333333333333

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
X = cv.fit_transform(df['Text'])

print("Vocabulary:", cv.get_feature_names_out())
print("Term Frequency (Document-Term Matrix):\n", X.toarray())

C:\Users\verma\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

NameError: name 'df' is not defined

In [ ]:
tfidf = TfidfVectorizer(use_idf=True)
X_tfidf = tfidf.fit_transform(df['Text'])

# TF-IDF values
print("TF-IDF Matrix:\n", X_tfidf.toarray())

# To see Term Frequency (before IDF is applied)
tfidf_no_idf = TfidfVectorizer(use_idf=False, norm=None)  # disables IDF
X_tf = tfidf_no_idf.fit_transform(df['Text'])
print("Term Frequency:\n", X_tf.toarray())

print("Vocabulary:", tfidf_no_idf.get_feature_names_out())