In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('diabetes (2).csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [3]:
X=df.drop(columns=['Outcome'])
y=df['Outcome']

In [4]:
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
st=StandardScaler()
x_scaled=st.fit_transform(X)
x_scaled

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [9]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [10]:
model=Sequential()

model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid',input_dim=8))

model.summary()

C:\Users\cipl\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                  │             288 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [12]:
model.fit(x_train,y_train,epochs=100,batch_size=32,validation_data=(x_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.5867 - loss: 5.1958 - val_accuracy: 0.5519 - val_loss: 2.4165
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6091 - loss: 1.6523 - val_accuracy: 0.5844 - val_loss: 1.4413
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6417 - loss: 1.3182 - val_accuracy: 0.5974 - val_loss: 1.2562
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6099 - loss: 1.1867 - val_accuracy: 0.6299 - val_loss: 1.0504
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6440 - loss: 0.9879 - val_accuracy: 0.6234 - val_loss: 1.0190
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6533 - loss: 0.9004 - val_accuracy: 0.5974 - val_loss: 1.0074
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6362 - loss: 0.8372 - val_accuracy: 0.6039 - val_loss: 0.9462
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6550 - loss: 0.8402 - val_accuracy: 0.5844 - val_loss: 0.8780
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6147 - loss: 0.9305 - val_accuracy: 0.5974 - val_loss: 0.9374
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6497 - loss: 0.8613 - val_accuracy: 0.6169 - val_loss: 0.9134
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6400 - loss: 0.8083 - val_accuracy: 0.5455 - val_loss: 0.9590
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6679 - loss: 0.7163 - val_accuracy: 0.6104 - val_loss: 0.8779
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6591 - loss: 0.7325 - val_accuracy: 0.6039 - val_loss: 0.8535
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6952 - loss: 0.6577 - val_accuracy: 0.6104 - val_loss: 0.8973
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6683 - loss: 0.7174 - val_accuracy: 0.6039 - val_loss: 0.8813
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6978 - loss: 0.6605 - val_accuracy: 0.5974 - val_loss: 0.8437
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6944 - loss: 0.6190 - val_accuracy: 0.5844 - val_loss: 0.8243
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6873 - loss: 0.6328 - val_accuracy: 0.5974 - val_loss: 0.8305
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6664 - loss: 0.6642 - val_accuracy: 0.6104 - val_loss: 0.8259
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6491 - loss: 0.6954 - val_accuracy: 0.5974 - val_loss: 0.7995
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7002 - loss: 0.6246 - val_accuracy: 0.6494 - val_loss: 0.9497
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6954 - loss: 0.6763 - val_accuracy: 0.6364 - val_loss: 0.8018
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7173 - loss: 0.5991 - val_accuracy: 0.6169 - val_loss: 0.7749
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7252 - loss: 0.5712 - val_accuracy: 0.6104 - val_loss: 0.8017
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6808 - loss: 0.7187 - val_accuracy: 0.6429 - val_loss: 0.8391
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7690 - loss: 0.5556 - val_accuracy: 0.5974 - val_loss: 0.8268
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6752 - loss: 0.6412 - val_accuracy: 0.6429 - val_loss: 0.7747
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7187 - loss: 0.6064 - val_accuracy: 0.6429 - val_loss: 0.7836
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7335 - loss: 0.5740 - val_accuracy: 0.6558 - val_loss: 0.8127
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7050 - loss: 0.5807 - val_accuracy: 0.6558 - val_loss: 0.7702
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7120 - loss: 0.5774 - val_accuracy: 0.6494 - val_loss: 0.7556
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7286 - loss: 0.5678 - val_accuracy: 0.6494 - val_loss: 0.7829
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6920 - loss: 0.6215 - val_accuracy: 0.6494 - val_loss: 0.7724
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7241 - loss: 0.5681 - val_accuracy: 0.6688 - val_loss: 0.7536
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7040 - loss: 0.5996 - val_accuracy: 0.6818 - val_loss: 0.7923
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7118 - loss: 0.5826 - val_accuracy: 0.6558 - val_loss: 0.7614
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7316 - loss: 0.5806 - val_accuracy: 0.6429 - val_loss: 0.7683
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7185 - loss: 0.5841 - val_accuracy: 0.6623 - val_loss: 0.7511
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7360 - loss: 0.5315 - val_accuracy: 0.6494 - val_loss: 0.7398
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7299 - loss: 0.5700 - val_accuracy: 0.6623 - val_loss: 0.7289
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7506 - loss: 0.5538 - val_accuracy: 0.6688 - val_loss: 0.7317
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7222 - loss: 0.5647 - val_accuracy: 0.6948 - val_loss: 0.7259
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7143 - loss: 0.6135 - val_accuracy: 0.6883 - val_loss: 0.7621
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7055 - loss: 0.5875 - val_accuracy: 0.6753 - val_loss: 0.7511
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7235 - loss: 0.5482 - val_accuracy: 0.6494 - val_loss: 0.7374
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7595 - loss: 0.5721 - val_accuracy: 0.6688 - val_loss: 0.8103
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7258 - loss: 0.5768 - val_accuracy: 0.6558 - val_loss: 0.7195
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7221 - loss: 0.5367 - val_accuracy: 0.6494 - val_loss: 0.7149
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7034 - loss: 0.5770 - val_accuracy: 0.6948 - val_loss: 0.7152
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7245 - loss: 0.5390 - val_accuracy: 0.6558 - val_loss: 0.7186
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7077 - loss: 0.5509 - val_accuracy: 0.6948 - val_loss: 0.7158
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7381 - loss: 0.5407 - val_accuracy: 0.7078 - val_loss: 0.7518
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7176 - loss: 0.5610 - val_accuracy: 0.6688 - val_loss: 0.7099
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7394 - loss: 0.5364 - val_accuracy: 0.6883 - val_loss: 0.7134
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7385 - loss: 0.5571 - val_accuracy: 0.6883 - val_loss: 0.7017
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6741 - loss: 0.5872 - val_accuracy: 0.6558 - val_loss: 0.7165
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7332 - loss: 0.5284 - val_accuracy: 0.7013 - val_loss: 0.7630
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7115 - loss: 0.6050 - val_accuracy: 0.6818 - val_loss: 0.7060
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7421 - loss: 0.5137 - val_accuracy: 0.6169 - val_loss: 0.7629
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6845 - loss: 0.6099 - val_accuracy: 0.6883 - val_loss: 0.7363
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7378 - loss: 0.5579 - val_accuracy: 0.6623 - val_loss: 0.7046
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7509 - loss: 0.5369 - val_accuracy: 0.6818 - val_loss: 0.8015
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7438 - loss: 0.5358 - val_accuracy: 0.6948 - val_loss: 0.7014
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7524 - loss: 0.5420 - val_accuracy: 0.6753 - val_loss: 0.6999
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7568 - loss: 0.5845 - val_accuracy: 0.6364 - val_loss: 0.7634
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6940 - loss: 0.5566 - val_accuracy: 0.6558 - val_loss: 0.7270
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7372 - loss: 0.5373 - val_accuracy: 0.6558 - val_loss: 0.7048
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7360 - loss: 0.5370 - val_accuracy: 0.6948 - val_loss: 0.7066
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6987 - loss: 0.5582 - val_accuracy: 0.6818 - val_loss: 0.7309
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7849 - loss: 0.5130 - val_accuracy: 0.6948 - val_loss: 0.7023
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7593 - loss: 0.5012 - val_accuracy: 0.6169 - val_loss: 0.7566
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7486 - loss: 0.5272 - val_accuracy: 0.6883 - val_loss: 0.7027
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7351 - loss: 0.5192 - val_accuracy: 0.6494 - val_loss: 0.7156
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7478 - loss: 0.5252 - val_accuracy: 0.6688 - val_loss: 0.7043
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7361 - loss: 0.5350 - val_accuracy: 0.6558 - val_loss: 0.7018
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7396 - loss: 0.5505 - val_accuracy: 0.6688 - val_loss: 0.7282
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7516 - loss: 0.5455 - val_accuracy: 0.7078 - val_loss: 0.7802
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7377 - loss: 0.5164 - val_accuracy: 0.6558 - val_loss: 0.7212
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7205 - loss: 0.5718 - val_accuracy: 0.6558 - val_loss: 0.7095
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7362 - loss: 0.5437 - val_accuracy: 0.6753 - val_loss: 0.7605
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7614 - loss: 0.5189 - val_accuracy: 0.7013 - val_loss: 0.7544
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7133 - loss: 0.5604 - val_accuracy: 0.6688 - val_loss: 0.7047
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7635 - loss: 0.5545 - val_accuracy: 0.7078 - val_loss: 0.7128
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7665 - loss: 0.5253 - val_accuracy: 0.6948 - val_loss: 0.7183
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7480 - loss: 0.5307 - val_accuracy: 0.7013 - val_loss: 0.7059
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7045 - loss: 0.5248 - val_accuracy: 0.7208 - val_loss: 0.7294
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7487 - loss: 0.5370 - val_accuracy: 0.7143 - val_loss: 0.7148
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7246 - loss: 0.5639 - val_accuracy: 0.6494 - val_loss: 0.7312
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7206 - loss: 0.5402 - val_accuracy: 0.7013 - val_loss: 0.7239
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7347 - loss: 0.5417 - val_accuracy: 0.6883 - val_loss: 0.6945
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6866 - loss: 0.6192 - val_accuracy: 0.6234 - val_loss: 0.7825
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7362 - loss: 0.5298 - val_accuracy: 0.6948 - val_loss: 0.7447
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7258 - loss: 0.5688 - val_accuracy: 0.7013 - val_loss: 0.6589
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7249 - loss: 0.5589 - val_accuracy: 0.6688 - val_loss: 0.6774
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7129 - loss: 0.5515 - val_accuracy: 0.6948 - val_loss: 0.7264
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7397 - loss: 0.5394 - val_accuracy: 0.6429 - val_loss: 0.6664
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7661 - loss: 0.5179 - val_accuracy: 0.6948 - val_loss: 0.6793
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7477 - loss: 0.5513 - val_accuracy: 0.6948 - val_loss: 0.7336
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7372 - loss: 0.5508 - val_accuracy: 0.6688 - val_loss: 0.6628
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7754 - loss: 0.5073 - val_accuracy: 0.7013 - val_loss: 0.6925

In [13]:
# How to Select a Appropriate Optimizer
# No of Nodes in a layer
# How to select no of layers
# All in all one model

# How to Select a Appropriate Optimizer

In [14]:
#pip install -U keras-tuner

In [15]:
import kerastuner as kt

C:\Users\cipl\AppData\Local\Temp\ipykernel_10396\1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [16]:
def build_model(hp):

    model=Sequential()
    model.add(Dense(32,activation='relu',input_dim=8))
    model.add(Dense(1,activation='sigmoid'))


    optimizers=hp.Choice('optimizers',values=['sgd','adam','rmsprop','adadelta'])

    model.compile(optimizer=optimizers,loss='binary_crossentropy',metrics=['accuracy'])

    return model

In [17]:
tuner=kt.RandomSearch(build_model,
                objective='val_accuracy',
                max_trials=5)

C:\Users\cipl\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [18]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.6363636255264282

Best val_accuracy So Far: 0.6363636255264282
Total elapsed time: 00h 00m 13s

In [21]:
tuner.get_best_hyperparameters()[0].values

{'optimizers': 'rmsprop'}

In [23]:
model=tuner.get_best_models(num_models=1)[0]

In [25]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=5,validation_data=(x_test,y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.5698 - loss: 1.5302 - val_accuracy: 0.5455 - val_loss: 1.3764
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5987 - loss: 1.0658 - val_accuracy: 0.6299 - val_loss: 1.1634
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6414 - loss: 0.9842 - val_accuracy: 0.6299 - val_loss: 0.9847
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6463 - loss: 0.9267 - val_accuracy: 0.4870 - val_loss: 1.6666
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6482 - loss: 0.9448 - val_accuracy: 0.6494 - val_loss: 1.2471
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6266 - loss: 0.9997 - val_accuracy: 0.6429 - val_loss: 1.0960
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6090 - loss: 0.8893 - val_accuracy: 0.5325 - val_loss: 1.0679
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6322 - loss: 0.8464 - val_accuracy: 0.6494 - val_loss: 1.4174
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6222 - loss: 0.9311 - val_accuracy: 0.6623 - val_loss: 1.1541
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6654 - loss: 0.8917 - val_accuracy: 0.6364 - val_loss: 0.8035
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6514 - loss: 0.7840 - val_accuracy: 0.4805 - val_loss: 1.4108
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5828 - loss: 0.9210 - val_accuracy: 0.6494 - val_loss: 1.0553
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6532 - loss: 0.7807 - val_accuracy: 0.6039 - val_loss: 0.8860
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6826 - loss: 0.7376 - val_accuracy: 0.3896 - val_loss: 2.0298
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6104 - loss: 0.9479 - val_accuracy: 0.6753 - val_loss: 0.9368
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6657 - loss: 0.7617 - val_accuracy: 0.6169 - val_loss: 0.8324
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6229 - loss: 0.7806 - val_accuracy: 0.6753 - val_loss: 0.9425
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6672 - loss: 0.7570 - val_accuracy: 0.4416 - val_loss: 1.4766
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6306 - loss: 0.8827 - val_accuracy: 0.6688 - val_loss: 0.8420
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6130 - loss: 0.8549 - val_accuracy: 0.5260 - val_loss: 1.1175
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6293 - loss: 0.7740 - val_accuracy: 0.4740 - val_loss: 1.3712
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6945 - loss: 0.7294 - val_accuracy: 0.6364 - val_loss: 0.9479
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6787 - loss: 0.6754 - val_accuracy: 0.5779 - val_loss: 0.9115
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6682 - loss: 0.7735 - val_accuracy: 0.6818 - val_loss: 0.7998
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6931 - loss: 0.7082 - val_accuracy: 0.6558 - val_loss: 1.4201
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6594 - loss: 0.8062 - val_accuracy: 0.5390 - val_loss: 0.9931
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6729 - loss: 0.7204 - val_accuracy: 0.6429 - val_loss: 0.8766
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6688 - loss: 0.7523 - val_accuracy: 0.6558 - val_loss: 0.7333
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6955 - loss: 0.6695 - val_accuracy: 0.5390 - val_loss: 0.9560
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6794 - loss: 0.7470 - val_accuracy: 0.6753 - val_loss: 0.8418
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6881 - loss: 0.7039 - val_accuracy: 0.6104 - val_loss: 0.7890
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6394 - loss: 0.7959 - val_accuracy: 0.6623 - val_loss: 0.9677
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6962 - loss: 0.6737 - val_accuracy: 0.6753 - val_loss: 0.8703
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7039 - loss: 0.6248 - val_accuracy: 0.6688 - val_loss: 0.8548
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7090 - loss: 0.7029 - val_accuracy: 0.5000 - val_loss: 1.2367
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6523 - loss: 0.7414 - val_accuracy: 0.5260 - val_loss: 1.3136
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6553 - loss: 0.7328 - val_accuracy: 0.6948 - val_loss: 0.7852
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6799 - loss: 0.6574 - val_accuracy: 0.6818 - val_loss: 0.7379
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6983 - loss: 0.6352 - val_accuracy: 0.5325 - val_loss: 1.1481
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6744 - loss: 0.7115 - val_accuracy: 0.6429 - val_loss: 0.9655
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6858 - loss: 0.7184 - val_accuracy: 0.4675 - val_loss: 1.5569
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6126 - loss: 0.9071 - val_accuracy: 0.6169 - val_loss: 0.8201
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6822 - loss: 0.6887 - val_accuracy: 0.6623 - val_loss: 0.7282
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6734 - loss: 0.7025 - val_accuracy: 0.6558 - val_loss: 0.9636
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6971 - loss: 0.6242 - val_accuracy: 0.6623 - val_loss: 0.8183
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7327 - loss: 0.6229 - val_accuracy: 0.6558 - val_loss: 1.1853
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7174 - loss: 0.6370 - val_accuracy: 0.6494 - val_loss: 0.9825
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7003 - loss: 0.6427 - val_accuracy: 0.6494 - val_loss: 0.8347
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6895 - loss: 0.6921 - val_accuracy: 0.6429 - val_loss: 0.8681
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6819 - loss: 0.6404 - val_accuracy: 0.6818 - val_loss: 0.8525
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6918 - loss: 0.6937 - val_accuracy: 0.6558 - val_loss: 1.0788
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6543 - loss: 0.7674 - val_accuracy: 0.6688 - val_loss: 0.7655
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6980 - loss: 0.7433 - val_accuracy: 0.6883 - val_loss: 0.7901
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7049 - loss: 0.6698 - val_accuracy: 0.6558 - val_loss: 0.7358
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6896 - loss: 0.6347 - val_accuracy: 0.5195 - val_loss: 1.0602
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6911 - loss: 0.6591 - val_accuracy: 0.6558 - val_loss: 0.7266
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7365 - loss: 0.5836 - val_accuracy: 0.6364 - val_loss: 0.7699
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6968 - loss: 0.6688 - val_accuracy: 0.6818 - val_loss: 0.7773
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7082 - loss: 0.6540 - val_accuracy: 0.6429 - val_loss: 1.2868
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7377 - loss: 0.6247 - val_accuracy: 0.6429 - val_loss: 1.2860
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6921 - loss: 0.7143 - val_accuracy: 0.6883 - val_loss: 0.8548
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6547 - loss: 0.7482 - val_accuracy: 0.6688 - val_loss: 1.0782
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6980 - loss: 0.6556 - val_accuracy: 0.6494 - val_loss: 0.9113
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6648 - loss: 0.6818 - val_accuracy: 0.6558 - val_loss: 0.7803
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6729 - loss: 0.7049 - val_accuracy: 0.6753 - val_loss: 0.7804
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6852 - loss: 0.7241 - val_accuracy: 0.6623 - val_loss: 0.7519
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6968 - loss: 0.6417 - val_accuracy: 0.6623 - val_loss: 0.8516
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7023 - loss: 0.6254 - val_accuracy: 0.6494 - val_loss: 1.1344
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7153 - loss: 0.6116 - val_accuracy: 0.6818 - val_loss: 0.7962
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6961 - loss: 0.6487 - val_accuracy: 0.7078 - val_loss: 0.7741
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7053 - loss: 0.6357 - val_accuracy: 0.6688 - val_loss: 0.9620
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6983 - loss: 0.6731 - val_accuracy: 0.6429 - val_loss: 0.7797
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6919 - loss: 0.6293 - val_accuracy: 0.6558 - val_loss: 1.1528
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6889 - loss: 0.6866 - val_accuracy: 0.6623 - val_loss: 0.7819
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7144 - loss: 0.6702 - val_accuracy: 0.6688 - val_loss: 0.8477
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7040 - loss: 0.6164 - val_accuracy: 0.6753 - val_loss: 0.8261
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6776 - loss: 0.6868 - val_accuracy: 0.6818 - val_loss: 0.8824
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7077 - loss: 0.6328 - val_accuracy: 0.5909 - val_loss: 0.8331
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6733 - loss: 0.7357 - val_accuracy: 0.6753 - val_loss: 0.7501
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6677 - loss: 0.6577 - val_accuracy: 0.6688 - val_loss: 0.7344
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7078 - loss: 0.6045 - val_accuracy: 0.6558 - val_loss: 0.8210
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6909 - loss: 0.6335 - val_accuracy: 0.5519 - val_loss: 0.9497
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6904 - loss: 0.5922 - val_accuracy: 0.5195 - val_loss: 1.1468
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6790 - loss: 0.6528 - val_accuracy: 0.6883 - val_loss: 0.8455
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7045 - loss: 0.6225 - val_accuracy: 0.6818 - val_loss: 0.7777
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6824 - loss: 0.6308 - val_accuracy: 0.6688 - val_loss: 0.9161
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6863 - loss: 0.6712 - val_accuracy: 0.6948 - val_loss: 0.7789
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7316 - loss: 0.5955 - val_accuracy: 0.6688 - val_loss: 0.8861
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7361 - loss: 0.5841 - val_accuracy: 0.6558 - val_loss: 0.7751
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6939 - loss: 0.6428 - val_accuracy: 0.6429 - val_loss: 1.2236
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7182 - loss: 0.6236 - val_accuracy: 0.6818 - val_loss: 0.7322
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7087 - loss: 0.6078 - val_accuracy: 0.6753 - val_loss: 1.0153
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6987 - loss: 0.6344 - val_accuracy: 0.6688 - val_loss: 0.7680
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6965 - loss: 0.6773 - val_accuracy: 0.6429 - val_loss: 1.2847
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6913 - loss: 0.6718 - val_accuracy: 0.4870 - val_loss: 1.2519

# No of Nodes in a layer

In [26]:
def build_model(hp):
    model=Sequential()
    units=hp.Int('units',min_value=8,max_value=128)
    model.add(Dense(units,activation='relu',input_dim=8))
    model.add(Dense(1,activation='sigmoid'))


    model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

    return model

In [27]:
tuner=kt.RandomSearch(build_model,
                objective='val_accuracy',
                max_trials=5,
                directory='mydir',
                project_name='deepanshu')

C:\Users\cipl\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [28]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.6558441519737244

Best val_accuracy So Far: 0.6753246784210205
Total elapsed time: 00h 00m 14s

In [29]:
tuner.get_best_hyperparameters()[0].values

{'units': 85}

In [30]:
model=tuner.get_best_models(num_models=1)[0]

C:\Users\cipl\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\cipl\AppData\Roaming\Python\Python312\site-packages\keras\src\saving\saving_lib.py:719: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [31]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=5,validation_data=(x_test,y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.5875 - loss: 1.3271 - val_accuracy: 0.3701 - val_loss: 2.2857
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.6252 - loss: 0.9663 - val_accuracy: 0.6429 - val_loss: 1.7451
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6696 - loss: 0.9563 - val_accuracy: 0.6364 - val_loss: 0.7005
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6737 - loss: 0.7139 - val_accuracy: 0.5390 - val_loss: 0.9059
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6752 - loss: 0.7238 - val_accuracy: 0.6558 - val_loss: 0.7444
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6703 - loss: 0.8667 - val_accuracy: 0.6494 - val_loss: 1.0908
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6314 - loss: 0.8520 - val_accuracy: 0.6753 - val_loss: 0.8301
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6854 - loss: 0.7315 - val_accuracy: 0.3506 - val_loss: 2.7400
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6319 - loss: 0.9583 - val_accuracy: 0.6429 - val_loss: 1.1786
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6690 - loss: 0.8212 - val_accuracy: 0.6558 - val_loss: 1.1761
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6477 - loss: 0.7649 - val_accuracy: 0.6429 - val_loss: 1.5180
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6705 - loss: 0.8091 - val_accuracy: 0.6429 - val_loss: 0.7195
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6571 - loss: 0.8030 - val_accuracy: 0.6039 - val_loss: 1.1690
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6732 - loss: 0.8379 - val_accuracy: 0.7143 - val_loss: 0.7373
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7260 - loss: 0.6459 - val_accuracy: 0.6494 - val_loss: 1.3238
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6923 - loss: 0.7570 - val_accuracy: 0.6234 - val_loss: 0.8257
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6975 - loss: 0.6953 - val_accuracy: 0.6948 - val_loss: 0.7281
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7246 - loss: 0.6742 - val_accuracy: 0.6429 - val_loss: 1.5534
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6675 - loss: 0.9865 - val_accuracy: 0.7143 - val_loss: 0.7114
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7330 - loss: 0.6288 - val_accuracy: 0.5649 - val_loss: 1.0516
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6468 - loss: 0.8889 - val_accuracy: 0.7208 - val_loss: 0.8261
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7321 - loss: 0.6812 - val_accuracy: 0.6558 - val_loss: 0.8018
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6776 - loss: 0.7054 - val_accuracy: 0.5649 - val_loss: 1.3345
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6836 - loss: 0.7123 - val_accuracy: 0.7013 - val_loss: 0.8681
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7074 - loss: 0.6488 - val_accuracy: 0.6948 - val_loss: 1.4188
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6756 - loss: 0.7795 - val_accuracy: 0.6429 - val_loss: 1.7309
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7132 - loss: 0.6961 - val_accuracy: 0.6818 - val_loss: 1.0146
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6996 - loss: 0.6532 - val_accuracy: 0.6429 - val_loss: 1.6894
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6965 - loss: 0.7890 - val_accuracy: 0.4091 - val_loss: 1.6903
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6029 - loss: 0.9577 - val_accuracy: 0.6753 - val_loss: 1.0672
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7629 - loss: 0.5974 - val_accuracy: 0.6494 - val_loss: 1.6887
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6965 - loss: 0.7635 - val_accuracy: 0.6039 - val_loss: 0.9922
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6355 - loss: 0.7562 - val_accuracy: 0.4221 - val_loss: 1.5902
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5832 - loss: 0.9619 - val_accuracy: 0.4091 - val_loss: 1.7573
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6665 - loss: 0.8653 - val_accuracy: 0.6558 - val_loss: 0.9496
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7574 - loss: 0.5869 - val_accuracy: 0.4156 - val_loss: 2.0723
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6539 - loss: 0.8611 - val_accuracy: 0.7078 - val_loss: 0.6974
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6784 - loss: 0.7666 - val_accuracy: 0.6688 - val_loss: 0.7829
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6578 - loss: 0.7849 - val_accuracy: 0.6299 - val_loss: 0.8375
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7103 - loss: 0.6749 - val_accuracy: 0.6169 - val_loss: 0.8470
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6970 - loss: 0.6808 - val_accuracy: 0.7468 - val_loss: 0.7567
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7031 - loss: 0.6460 - val_accuracy: 0.5649 - val_loss: 0.9972
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6881 - loss: 0.6887 - val_accuracy: 0.7143 - val_loss: 0.7108
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7046 - loss: 0.6868 - val_accuracy: 0.6494 - val_loss: 1.9399
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7215 - loss: 0.8167 - val_accuracy: 0.6753 - val_loss: 0.8571
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6829 - loss: 0.7512 - val_accuracy: 0.6558 - val_loss: 1.3086
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6668 - loss: 0.8749 - val_accuracy: 0.7078 - val_loss: 0.8885
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6493 - loss: 0.7436 - val_accuracy: 0.5455 - val_loss: 1.0442
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6201 - loss: 0.8864 - val_accuracy: 0.5000 - val_loss: 1.0995
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7002 - loss: 0.6991 - val_accuracy: 0.5260 - val_loss: 1.1559
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6321 - loss: 0.8707 - val_accuracy: 0.6948 - val_loss: 0.7571
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6883 - loss: 0.7258 - val_accuracy: 0.7273 - val_loss: 0.8343
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6992 - loss: 0.6962 - val_accuracy: 0.6558 - val_loss: 1.0469
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6956 - loss: 0.7339 - val_accuracy: 0.6883 - val_loss: 0.7709
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6984 - loss: 0.6137 - val_accuracy: 0.7273 - val_loss: 0.7646
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7146 - loss: 0.6632 - val_accuracy: 0.6883 - val_loss: 0.9136
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7193 - loss: 0.5985 - val_accuracy: 0.5260 - val_loss: 1.3270
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7105 - loss: 0.7040 - val_accuracy: 0.4545 - val_loss: 1.2939
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6747 - loss: 0.7194 - val_accuracy: 0.7338 - val_loss: 0.7725
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6632 - loss: 0.7543 - val_accuracy: 0.5974 - val_loss: 0.8960
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7183 - loss: 0.6961 - val_accuracy: 0.7273 - val_loss: 0.7818
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6844 - loss: 0.7777 - val_accuracy: 0.7078 - val_loss: 0.8740
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7252 - loss: 0.6470 - val_accuracy: 0.6558 - val_loss: 1.3334
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7205 - loss: 0.7539 - val_accuracy: 0.7273 - val_loss: 0.8462
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6908 - loss: 0.6879 - val_accuracy: 0.6948 - val_loss: 0.9459
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7115 - loss: 0.6039 - val_accuracy: 0.4156 - val_loss: 1.7242
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6613 - loss: 0.7990 - val_accuracy: 0.7013 - val_loss: 1.0551
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6554 - loss: 0.8593 - val_accuracy: 0.6494 - val_loss: 1.6614
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6844 - loss: 0.8107 - val_accuracy: 0.6494 - val_loss: 1.4771
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6571 - loss: 0.8560 - val_accuracy: 0.6948 - val_loss: 0.8940
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7054 - loss: 0.7266 - val_accuracy: 0.6948 - val_loss: 1.0261
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6954 - loss: 0.6894 - val_accuracy: 0.7143 - val_loss: 0.8588
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6778 - loss: 0.7407 - val_accuracy: 0.4545 - val_loss: 1.3047
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7367 - loss: 0.6671 - val_accuracy: 0.4091 - val_loss: 2.1960
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6800 - loss: 0.8007 - val_accuracy: 0.6623 - val_loss: 0.8802
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6659 - loss: 0.8009 - val_accuracy: 0.6818 - val_loss: 1.0952
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6612 - loss: 0.7849 - val_accuracy: 0.7143 - val_loss: 0.8173
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7117 - loss: 0.6087 - val_accuracy: 0.5325 - val_loss: 1.5900
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7030 - loss: 0.7858 - val_accuracy: 0.6623 - val_loss: 1.2492
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6559 - loss: 0.7894 - val_accuracy: 0.6494 - val_loss: 1.7242
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6936 - loss: 0.7895 - val_accuracy: 0.7013 - val_loss: 1.0095
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7026 - loss: 0.6934 - val_accuracy: 0.5000 - val_loss: 1.4599
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6949 - loss: 0.7582 - val_accuracy: 0.5584 - val_loss: 1.1569
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7042 - loss: 0.6885 - val_accuracy: 0.4156 - val_loss: 2.1821
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6670 - loss: 0.8955 - val_accuracy: 0.6558 - val_loss: 1.4146
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7094 - loss: 0.6935 - val_accuracy: 0.6753 - val_loss: 1.6743
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7210 - loss: 0.7966 - val_accuracy: 0.6948 - val_loss: 0.8211
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7233 - loss: 0.6188 - val_accuracy: 0.7403 - val_loss: 0.8126
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6737 - loss: 0.7569 - val_accuracy: 0.7273 - val_loss: 0.7906
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6954 - loss: 0.6755 - val_accuracy: 0.6494 - val_loss: 0.9339
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6732 - loss: 0.7086 - val_accuracy: 0.5260 - val_loss: 1.2672
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6696 - loss: 0.9213 - val_accuracy: 0.7078 - val_loss: 0.8022
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7195 - loss: 0.5865 - val_accuracy: 0.6429 - val_loss: 1.5687
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6938 - loss: 0.7355 - val_accuracy: 0.5779 - val_loss: 1.0743
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7287 - loss: 0.6040 - val_accuracy: 0.6883 - val_loss: 0.9737

# How to select no of layers

In [33]:
def build_model(hp):
    model=Sequential()
    model.add(Dense(85,activation='relu',input_dim=8))

    for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
        model.add(Dense(85,activation='relu'))

    model.add(Dense(1,activation='sigmoid'))

    model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

    return model

In [35]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=3,directory='mydir',project_name='verma')

In [36]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.649350643157959

Best val_accuracy So Far: 0.6948052048683167
Total elapsed time: 00h 00m 12s

In [37]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 10}

In [38]:
model=tuner.get_best_models(num_models=1)[0]

C:\Users\cipl\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\cipl\AppData\Roaming\Python\Python312\site-packages\keras\src\saving\saving_lib.py:719: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 26 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [39]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=5,validation_data=(x_test,y_test))

Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - accuracy: 0.6776 - loss: 0.6288 - val_accuracy: 0.5974 - val_loss: 0.6690
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6368 - loss: 0.6112 - val_accuracy: 0.6558 - val_loss: 0.6728
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6932 - loss: 0.5858 - val_accuracy: 0.6429 - val_loss: 0.6947
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6654 - loss: 0.5935 - val_accuracy: 0.6818 - val_loss: 0.6826
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6917 - loss: 0.5818 - val_accuracy: 0.6753 - val_loss: 0.7211
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6880 - loss: 0.5953 - val_accuracy: 0.6948 - val_loss: 0.6687
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6555 - loss: 0.6123 - val_accuracy: 0.6818 - val_loss: 0.8857
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6999 - loss: 0.5536 - val_accuracy: 0.5714 - val_loss: 0.6796
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6883 - loss: 0.5689 - val_accuracy: 0.6818 - val_loss: 0.8297
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7557 - loss: 0.5213 - val_accuracy: 0.6688 - val_loss: 0.6627
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7038 - loss: 0.5461 - val_accuracy: 0.5714 - val_loss: 0.8623
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7060 - loss: 0.5665 - val_accuracy: 0.6883 - val_loss: 0.6636
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.5181 - val_accuracy: 0.6494 - val_loss: 0.7343
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7510 - loss: 0.5348 - val_accuracy: 0.6364 - val_loss: 0.9388
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7097 - loss: 0.5568 - val_accuracy: 0.6688 - val_loss: 0.7066
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7271 - loss: 0.5311 - val_accuracy: 0.6688 - val_loss: 0.6416
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7156 - loss: 0.5391 - val_accuracy: 0.6558 - val_loss: 0.7813
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7444 - loss: 0.5058 - val_accuracy: 0.7078 - val_loss: 0.7230
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7275 - loss: 0.5102 - val_accuracy: 0.7013 - val_loss: 0.6417
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5167 - val_accuracy: 0.6818 - val_loss: 0.6952
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7330 - loss: 0.5146 - val_accuracy: 0.6883 - val_loss: 0.7424
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6787 - loss: 0.5610 - val_accuracy: 0.7338 - val_loss: 0.7611
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7312 - loss: 0.5093 - val_accuracy: 0.5844 - val_loss: 0.7871
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7206 - loss: 0.5315 - val_accuracy: 0.5390 - val_loss: 0.7875
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7601 - loss: 0.5052 - val_accuracy: 0.6948 - val_loss: 1.0337
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7403 - loss: 0.5035 - val_accuracy: 0.6753 - val_loss: 0.9790
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7233 - loss: 0.5325 - val_accuracy: 0.7013 - val_loss: 0.7005
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7330 - loss: 0.4963 - val_accuracy: 0.6948 - val_loss: 1.1406
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7568 - loss: 0.5158 - val_accuracy: 0.7532 - val_loss: 0.7536
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7786 - loss: 0.4523 - val_accuracy: 0.6234 - val_loss: 1.1139
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7517 - loss: 0.4517 - val_accuracy: 0.6299 - val_loss: 1.0413
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7551 - loss: 0.4876 - val_accuracy: 0.6558 - val_loss: 0.8334
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7659 - loss: 0.4996 - val_accuracy: 0.7403 - val_loss: 0.6905
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7552 - loss: 0.4820 - val_accuracy: 0.7143 - val_loss: 1.0458
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7766 - loss: 0.4492 - val_accuracy: 0.7662 - val_loss: 0.9233
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7623 - loss: 0.4753 - val_accuracy: 0.7338 - val_loss: 1.1252
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7326 - loss: 0.5515 - val_accuracy: 0.6883 - val_loss: 0.9976
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7456 - loss: 0.4595 - val_accuracy: 0.5909 - val_loss: 1.0440
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7073 - loss: 0.5583 - val_accuracy: 0.6818 - val_loss: 1.1130
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7833 - loss: 0.4324 - val_accuracy: 0.7143 - val_loss: 1.2069
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7965 - loss: 0.4270 - val_accuracy: 0.5714 - val_loss: 1.1674
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7385 - loss: 0.5076 - val_accuracy: 0.7468 - val_loss: 1.0319
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7642 - loss: 0.4628 - val_accuracy: 0.6948 - val_loss: 1.2129
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7950 - loss: 0.4260 - val_accuracy: 0.7662 - val_loss: 0.9788
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8001 - loss: 0.4446 - val_accuracy: 0.6299 - val_loss: 1.2183
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7793 - loss: 0.4602 - val_accuracy: 0.7078 - val_loss: 1.0125
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7846 - loss: 0.4682 - val_accuracy: 0.6948 - val_loss: 1.0201
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8121 - loss: 0.4051 - val_accuracy: 0.7338 - val_loss: 0.9267
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7967 - loss: 0.4399 - val_accuracy: 0.7078 - val_loss: 1.2697
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7725 - loss: 0.4502 - val_accuracy: 0.7403 - val_loss: 1.2825
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7711 - loss: 0.4613 - val_accuracy: 0.7273 - val_loss: 1.0343
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8147 - loss: 0.4084 - val_accuracy: 0.7013 - val_loss: 1.5363
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8095 - loss: 0.4287 - val_accuracy: 0.6688 - val_loss: 1.1909
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8000 - loss: 0.4372 - val_accuracy: 0.6623 - val_loss: 1.8639
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8224 - loss: 0.4079 - val_accuracy: 0.7013 - val_loss: 1.1549
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8164 - loss: 0.4000 - val_accuracy: 0.6818 - val_loss: 1.5219
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7629 - loss: 0.4628 - val_accuracy: 0.6299 - val_loss: 1.5700
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8098 - loss: 0.4113 - val_accuracy: 0.7468 - val_loss: 0.8796
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8077 - loss: 0.4122 - val_accuracy: 0.7208 - val_loss: 1.0238
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8131 - loss: 0.3838 - val_accuracy: 0.7208 - val_loss: 1.2374
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8009 - loss: 0.4234 - val_accuracy: 0.6883 - val_loss: 1.3460
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8035 - loss: 0.4174 - val_accuracy: 0.6494 - val_loss: 1.0437
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8001 - loss: 0.3783 - val_accuracy: 0.6818 - val_loss: 1.9614
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7561 - loss: 0.4775 - val_accuracy: 0.5714 - val_loss: 1.5100
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7749 - loss: 0.4390 - val_accuracy: 0.7208 - val_loss: 0.8008
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8381 - loss: 0.3901 - val_accuracy: 0.7338 - val_loss: 1.4348
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8260 - loss: 0.3738 - val_accuracy: 0.6753 - val_loss: 1.5149
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7625 - loss: 0.4692 - val_accuracy: 0.6948 - val_loss: 1.4049
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7979 - loss: 0.3726 - val_accuracy: 0.7013 - val_loss: 1.7325
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8283 - loss: 0.3979 - val_accuracy: 0.7273 - val_loss: 1.8173
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8130 - loss: 0.3828 - val_accuracy: 0.6883 - val_loss: 3.3603
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7707 - loss: 0.4813 - val_accuracy: 0.6494 - val_loss: 1.3334
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8016 - loss: 0.3929 - val_accuracy: 0.7208 - val_loss: 1.3138
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8159 - loss: 0.3593 - val_accuracy: 0.7468 - val_loss: 1.4586
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7872 - loss: 0.4422 - val_accuracy: 0.7338 - val_loss: 1.9499
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8205 - loss: 0.3842 - val_accuracy: 0.7273 - val_loss: 1.3259
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8135 - loss: 0.3727 - val_accuracy: 0.7468 - val_loss: 1.2592
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3842 - val_accuracy: 0.7078 - val_loss: 1.1995
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8488 - loss: 0.3559 - val_accuracy: 0.7208 - val_loss: 1.1120
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8175 - loss: 0.3809 - val_accuracy: 0.7078 - val_loss: 1.6053
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8488 - loss: 0.3259 - val_accuracy: 0.7143 - val_loss: 1.6499
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8419 - loss: 0.3736 - val_accuracy: 0.7208 - val_loss: 1.6103
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8294 - loss: 0.3838 - val_accuracy: 0.6299 - val_loss: 2.0867
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8222 - loss: 0.3605 - val_accuracy: 0.7208 - val_loss: 1.9713
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8240 - loss: 0.3880 - val_accuracy: 0.7013 - val_loss: 1.1705
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8469 - loss: 0.3364 - val_accuracy: 0.6623 - val_loss: 1.4874
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8510 - loss: 0.3740 - val_accuracy: 0.7403 - val_loss: 1.5120
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8533 - loss: 0.3116 - val_accuracy: 0.7078 - val_loss: 2.2089
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8279 - loss: 0.3799 - val_accuracy: 0.6623 - val_loss: 2.7491
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8373 - loss: 0.3433 - val_accuracy: 0.6494 - val_loss: 3.8468
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7955 - loss: 0.4301 - val_accuracy: 0.7338 - val_loss: 2.8708
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8502 - loss: 0.3494 - val_accuracy: 0.6883 - val_loss: 2.2224
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8518 - loss: 0.3724 - val_accuracy: 0.6883 - val_loss: 2.2596
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8569 - loss: 0.3162 - val_accuracy: 0.7273 - val_loss: 2.3978
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8480 - loss: 0.3419 - val_accuracy: 0.7013 - val_loss: 2.3526

# All in all one model

In [74]:
def build_model(hp):
    model=Sequential()
    counter=0

    for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
        if counter==0:
            model.add(Dense(hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
                            activation=hp.Choice('activation'+str(i),values=['relu','tanh','sigmoid']),
                            input_dim=8))

        else:
            model.add(Dense(hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
                            activation=hp.Choice('activation'+str(i),values=['relu','tanh','sigmoid'])))


        counter+=1

    
    model.add(Dense(1,activation='sigmoid'))

    model.compile(optimizer=hp.Choice('optimizer',values=['sgd','adam','rmsprop','adadelta']),
            loss='binary_crossentropy',metrics=['accuracy'])
    #print('hello')

    return model

In [75]:
tuner=kt.RandomSearch(build_model,
                objective='val_accuracy',
                max_trials=4,
                directory='mydir',
                project_name='final')

Reloading Tuner from mydir\final\tuner0.json

In [76]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

In [77]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 4,
 'units0': 104,
 'activation0': 'relu',
 'optimizer': 'adam',
 'units1': 56,
 'activation1': 'relu',
 'units2': 8,
 'activation2': 'sigmoid',
 'units3': 40,
 'activation3': 'sigmoid',
 'units4': 8,
 'activation4': 'tanh',
 'units5': 40,
 'activation5': 'relu',
 'units6': 104,
 'activation6': 'relu',
 'units7': 8,
 'activation7': 'relu'}

In [66]:
model=tuner.get_best_models(num_models=1)[0]

C:\Users\cipl\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\cipl\AppData\Roaming\Python\Python312\site-packages\keras\src\saving\saving_lib.py:719: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 22 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [67]:
model.fit(x_train,y_train,batch_size=32,epochs=200,initial_epoch=5,validation_data=(x_test,y_test))

Epoch 6/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.6485 - loss: 0.6574 - val_accuracy: 0.6429 - val_loss: 0.6514
Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6760 - loss: 0.6273 - val_accuracy: 0.6429 - val_loss: 0.6509
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6157 - loss: 0.6651 - val_accuracy: 0.6429 - val_loss: 0.6527
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6522 - loss: 0.6381 - val_accuracy: 0.6429 - val_loss: 0.6508
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6605 - loss: 0.6207 - val_accuracy: 0.6429 - val_loss: 0.6468
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6594 - loss: 0.6183 - val_accuracy: 0.6429 - val_loss: 0.6471
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6518 - loss: 0.6070 - val_accuracy: 0.6429 - val_loss: 0.6409
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6764 - loss: 0.5949 - val_accuracy: 0.6429 - val_loss: 0.6399
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6367 - loss: 0.6004 - val_accuracy: 0.6429 - val_loss: 0.6354
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6813 - loss: 0.5860 - val_accuracy: 0.6429 - val_loss: 0.6447
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6529 - loss: 0.6037 - val_accuracy: 0.6429 - val_loss: 0.6330
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6823 - loss: 0.5756 - val_accuracy: 0.6429 - val_loss: 0.6427
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6455 - loss: 0.6110 - val_accuracy: 0.6429 - val_loss: 0.6366
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6446 - loss: 0.6002 - val_accuracy: 0.6429 - val_loss: 0.6408
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6435 - loss: 0.6065 - val_accuracy: 0.6429 - val_loss: 0.6390
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6685 - loss: 0.5718 - val_accuracy: 0.6429 - val_loss: 0.6402
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6467 - loss: 0.5872 - val_accuracy: 0.6494 - val_loss: 0.6386
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6615 - loss: 0.5820 - val_accuracy: 0.6688 - val_loss: 0.6343
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6659 - loss: 0.5889 - val_accuracy: 0.6234 - val_loss: 0.6363
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6984 - loss: 0.5516 - val_accuracy: 0.6494 - val_loss: 0.6330
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6868 - loss: 0.5762 - val_accuracy: 0.6623 - val_loss: 0.6361
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6798 - loss: 0.5836 - val_accuracy: 0.6299 - val_loss: 0.6511
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6840 - loss: 0.5886 - val_accuracy: 0.5974 - val_loss: 0.6467
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6541 - loss: 0.6001 - val_accuracy: 0.6169 - val_loss: 0.6456
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6654 - loss: 0.5661 - val_accuracy: 0.6623 - val_loss: 0.6410
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6571 - loss: 0.5908 - val_accuracy: 0.6494 - val_loss: 0.6380
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7092 - loss: 0.5658 - val_accuracy: 0.6623 - val_loss: 0.6271
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6658 - loss: 0.5728 - val_accuracy: 0.6753 - val_loss: 0.6392
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6937 - loss: 0.5837 - val_accuracy: 0.6753 - val_loss: 0.6268
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6780 - loss: 0.5917 - val_accuracy: 0.6299 - val_loss: 0.6350
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6962 - loss: 0.5715 - val_accuracy: 0.6494 - val_loss: 0.6319
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7212 - loss: 0.5552 - val_accuracy: 0.6688 - val_loss: 0.6185
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7088 - loss: 0.5661 - val_accuracy: 0.6558 - val_loss: 0.6251
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7099 - loss: 0.5701 - val_accuracy: 0.6753 - val_loss: 0.6295
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6767 - loss: 0.5723 - val_accuracy: 0.6104 - val_loss: 0.6377
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6703 - loss: 0.5738 - val_accuracy: 0.6429 - val_loss: 0.6292
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7045 - loss: 0.5747 - val_accuracy: 0.6234 - val_loss: 0.6392
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6485 - loss: 0.5947 - val_accuracy: 0.6364 - val_loss: 0.6286
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6896 - loss: 0.5742 - val_accuracy: 0.6558 - val_loss: 0.6410
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6835 - loss: 0.5797 - val_accuracy: 0.6623 - val_loss: 0.6349
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6923 - loss: 0.5607 - val_accuracy: 0.6623 - val_loss: 0.6320
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6843 - loss: 0.5598 - val_accuracy: 0.6753 - val_loss: 0.6263
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6600 - loss: 0.5855 - val_accuracy: 0.6169 - val_loss: 0.6462
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6382 - loss: 0.5802 - val_accuracy: 0.6494 - val_loss: 0.6401
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7058 - loss: 0.5292 - val_accuracy: 0.6494 - val_loss: 0.6343
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6666 - loss: 0.5641 - val_accuracy: 0.6753 - val_loss: 0.6230
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6450 - loss: 0.5623 - val_accuracy: 0.6429 - val_loss: 0.6553
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6789 - loss: 0.5536 - val_accuracy: 0.6688 - val_loss: 0.6312
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6719 - loss: 0.5602 - val_accuracy: 0.6883 - val_loss: 0.6410
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6808 - loss: 0.5531 - val_accuracy: 0.6948 - val_loss: 0.6369
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6695 - loss: 0.5712 - val_accuracy: 0.6688 - val_loss: 0.6416
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6958 - loss: 0.5581 - val_accuracy: 0.6364 - val_loss: 0.6678
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6719 - loss: 0.5701 - val_accuracy: 0.6299 - val_loss: 0.6536
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7145 - loss: 0.5341 - val_accuracy: 0.6299 - val_loss: 0.6516
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7017 - loss: 0.5679 - val_accuracy: 0.7013 - val_loss: 0.6263
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7106 - loss: 0.5384 - val_accuracy: 0.6753 - val_loss: 0.6355
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7088 - loss: 0.5382 - val_accuracy: 0.6818 - val_loss: 0.6385
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7258 - loss: 0.5322 - val_accuracy: 0.6818 - val_loss: 0.6318
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6907 - loss: 0.5784 - val_accuracy: 0.6818 - val_loss: 0.6401
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6858 - loss: 0.5508 - val_accuracy: 0.6688 - val_loss: 0.6504
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7160 - loss: 0.5327 - val_accuracy: 0.6688 - val_loss: 0.6424
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6683 - loss: 0.5675 - val_accuracy: 0.6558 - val_loss: 0.6403
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.5453 - val_accuracy: 0.6364 - val_loss: 0.6484
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7092 - loss: 0.5506 - val_accuracy: 0.6364 - val_loss: 0.6466
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6968 - loss: 0.5244 - val_accuracy: 0.6429 - val_loss: 0.6432
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7360 - loss: 0.5340 - val_accuracy: 0.6818 - val_loss: 0.6239
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7234 - loss: 0.5348 - val_accuracy: 0.6688 - val_loss: 0.6454
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7043 - loss: 0.5300 - val_accuracy: 0.6429 - val_loss: 0.6422
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7274 - loss: 0.5307 - val_accuracy: 0.6169 - val_loss: 0.6514
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6976 - loss: 0.5581 - val_accuracy: 0.6688 - val_loss: 0.6386
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7021 - loss: 0.5334 - val_accuracy: 0.6494 - val_loss: 0.6410
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7060 - loss: 0.5562 - val_accuracy: 0.6558 - val_loss: 0.6543
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6993 - loss: 0.5486 - val_accuracy: 0.6494 - val_loss: 0.6452
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7009 - loss: 0.5481 - val_accuracy: 0.6104 - val_loss: 0.6603
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6941 - loss: 0.5598 - val_accuracy: 0.6494 - val_loss: 0.6527
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7040 - loss: 0.5300 - val_accuracy: 0.6623 - val_loss: 0.6489
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7124 - loss: 0.5363 - val_accuracy: 0.6818 - val_loss: 0.6382
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7045 - loss: 0.5313 - val_accuracy: 0.6494 - val_loss: 0.6342
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7233 - loss: 0.5355 - val_accuracy: 0.6688 - val_loss: 0.6503
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7142 - loss: 0.5315 - val_accuracy: 0.6753 - val_loss: 0.6287
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7076 - loss: 0.5209 - val_accuracy: 0.6364 - val_loss: 0.6486
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6850 - loss: 0.5718 - val_accuracy: 0.6299 - val_loss: 0.6493
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7031 - loss: 0.5369 - val_accuracy: 0.6429 - val_loss: 0.6488
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7086 - loss: 0.5406 - val_accuracy: 0.6688 - val_loss: 0.6290
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7193 - loss: 0.5303 - val_accuracy: 0.6818 - val_loss: 0.6287
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6817 - loss: 0.5558 - val_accuracy: 0.6494 - val_loss: 0.6330
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7210 - loss: 0.5546 - val_accuracy: 0.6818 - val_loss: 0.6334
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7218 - loss: 0.5200 - val_accuracy: 0.6364 - val_loss: 0.6564
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7019 - loss: 0.5257 - val_accuracy: 0.6299 - val_loss: 0.6493
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7037 - loss: 0.5253 - val_accuracy: 0.6429 - val_loss: 0.6467
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7222 - loss: 0.5013 - val_accuracy: 0.6429 - val_loss: 0.6540
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7093 - loss: 0.5221 - val_accuracy: 0.6558 - val_loss: 0.6622
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7223 - loss: 0.5707 - val_accuracy: 0.6494 - val_loss: 0.6435
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7341 - loss: 0.5111 - val_accuracy: 0.6623 - val_loss: 0.6496
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7547 - loss: 0.5040 - val_accuracy: 0.6883 - val_loss: 0.6260
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7399 - loss: 0.4954 - val_accuracy: 0.6364 - val_loss: 0.6397
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7151 - loss: 0.5095 - val_accuracy: 0.6818 - val_loss: 0.6342
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7643 - loss: 0.4811 - val_accuracy: 0.6818 - val_loss: 0.6313
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7279 - loss: 0.5290 - val_accuracy: 0.6883 - val_loss: 0.6256
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7165 - loss: 0.5189 - val_accuracy: 0.6299 - val_loss: 0.6613
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6984 - loss: 0.5419 - val_accuracy: 0.6623 - val_loss: 0.6427
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7288 - loss: 0.5153 - val_accuracy: 0.6623 - val_loss: 0.6545
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7382 - loss: 0.4931 - val_accuracy: 0.6623 - val_loss: 0.6320
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6958 - loss: 0.5252 - val_accuracy: 0.7013 - val_loss: 0.6314
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7051 - loss: 0.5428 - val_accuracy: 0.6429 - val_loss: 0.6466
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7152 - loss: 0.5348 - val_accuracy: 0.6688 - val_loss: 0.6282
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7607 - loss: 0.4840 - val_accuracy: 0.6883 - val_loss: 0.6304
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7554 - loss: 0.4939 - val_accuracy: 0.6948 - val_loss: 0.6281
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7275 - loss: 0.5292 - val_accuracy: 0.6948 - val_loss: 0.6048
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.5020 - val_accuracy: 0.7013 - val_loss: 0.6290
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7644 - loss: 0.4806 - val_accuracy: 0.7078 - val_loss: 0.6335
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7371 - loss: 0.5275 - val_accuracy: 0.7013 - val_loss: 0.6134
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7327 - loss: 0.5273 - val_accuracy: 0.7013 - val_loss: 0.6232
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7737 - loss: 0.4891 - val_accuracy: 0.6948 - val_loss: 0.6214
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7401 - loss: 0.5085 - val_accuracy: 0.6818 - val_loss: 0.6267
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7597 - loss: 0.4857 - val_accuracy: 0.7013 - val_loss: 0.6421
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7359 - loss: 0.5234 - val_accuracy: 0.6818 - val_loss: 0.6476
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7358 - loss: 0.5074 - val_accuracy: 0.6753 - val_loss: 0.6278
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7617 - loss: 0.4950 - val_accuracy: 0.6948 - val_loss: 0.6297
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7749 - loss: 0.4712 - val_accuracy: 0.7013 - val_loss: 0.6152
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7773 - loss: 0.4587 - val_accuracy: 0.7273 - val_loss: 0.6214
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7813 - loss: 0.4783 - val_accuracy: 0.6883 - val_loss: 0.6267
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7690 - loss: 0.4921 - val_accuracy: 0.6883 - val_loss: 0.6499
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7583 - loss: 0.4943 - val_accuracy: 0.7338 - val_loss: 0.6098
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7620 - loss: 0.4885 - val_accuracy: 0.7208 - val_loss: 0.6277
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7693 - loss: 0.4705 - val_accuracy: 0.6948 - val_loss: 0.6397
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7447 - loss: 0.4916 - val_accuracy: 0.6688 - val_loss: 0.6333
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7743 - loss: 0.4871 - val_accuracy: 0.6948 - val_loss: 0.6304
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7744 - loss: 0.4664 - val_accuracy: 0.6948 - val_loss: 0.6360
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7631 - loss: 0.4881 - val_accuracy: 0.7078 - val_loss: 0.6347
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7643 - loss: 0.4844 - val_accuracy: 0.7338 - val_loss: 0.6215
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7625 - loss: 0.4900 - val_accuracy: 0.6948 - val_loss: 0.6268
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7589 - loss: 0.4859 - val_accuracy: 0.7013 - val_loss: 0.6374
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7166 - loss: 0.5117 - val_accuracy: 0.7143 - val_loss: 0.6298
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7985 - loss: 0.4660 - val_accuracy: 0.6688 - val_loss: 0.6343
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7462 - loss: 0.5171 - val_accuracy: 0.7078 - val_loss: 0.6337
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7142 - loss: 0.4979 - val_accuracy: 0.7338 - val_loss: 0.6162
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7474 - loss: 0.4798 - val_accuracy: 0.6623 - val_loss: 0.6500
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7301 - loss: 0.4767 - val_accuracy: 0.6883 - val_loss: 0.6330
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7594 - loss: 0.4739 - val_accuracy: 0.6818 - val_loss: 0.6334
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7694 - loss: 0.4910 - val_accuracy: 0.7208 - val_loss: 0.6205
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7374 - loss: 0.5106 - val_accuracy: 0.7013 - val_loss: 0.6318
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6986 - loss: 0.5184 - val_accuracy: 0.7338 - val_loss: 0.6235
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7530 - loss: 0.4854 - val_accuracy: 0.7143 - val_loss: 0.6254
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7686 - loss: 0.4569 - val_accuracy: 0.6948 - val_loss: 0.6282
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7702 - loss: 0.4602 - val_accuracy: 0.7208 - val_loss: 0.6332
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7450 - loss: 0.5080 - val_accuracy: 0.7143 - val_loss: 0.6337
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7552 - loss: 0.4804 - val_accuracy: 0.6883 - val_loss: 0.6490
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7456 - loss: 0.4966 - val_accuracy: 0.6948 - val_loss: 0.6254
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7664 - loss: 0.4791 - val_accuracy: 0.7338 - val_loss: 0.6107
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8009 - loss: 0.4272 - val_accuracy: 0.7143 - val_loss: 0.6288
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4747 - val_accuracy: 0.7468 - val_loss: 0.6196
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7766 - loss: 0.4578 - val_accuracy: 0.7208 - val_loss: 0.6336
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7624 - loss: 0.4694 - val_accuracy: 0.7143 - val_loss: 0.6284
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7786 - loss: 0.4649 - val_accuracy: 0.7338 - val_loss: 0.6193
Epoch 161/200

In [78]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 104)                 │             936 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 56)                  │           5,880 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 8)                   │             456 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 40)                  │             360 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │              41 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 23,021 (89.93 KB)

 Trainable params: 7,673 (29.97 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 15,348 (59.96 KB)